### ISSUE TITLE
砍掉了推荐的“男生”、“女生”以及排行吗？

### ISSUE THREAD

**Issue by corn27** [390057892/reader#11]
作者您好，我刚接触移动应用开发，在学习测试这个项目时，发现推荐界面砍掉了“男生”、“女生”标签以及排行，但是readme截图里有，请问怎么才能把这些调出来呢？谢谢

**Comment by 390057892** [comment]
男生女生是一样的页面，就和你现在看到的推荐页是一样的。只是现在书源是轻小说的书源,不分男女，所以就用了一个页面展示。。还有推荐其实就是一个列表页面。你可以参考分类列表，只是多加了viewpage做了榜单切换。
