### ISSUE TITLE
有个问题想请教一下，假如内容是英文的文章呢？

### ISSUE THREAD

**Issue by luotext** [390057892/reader#14]
那么英文的文章是按照单词来的，和中文按照单个字来计算不一样，那么根据中文的排版，单词就被切割了，一个单词就被切割了一半到第二行去了，所以这个计算一行显示多少个单词，然后正确排版，不知道有什么办法呢?

**Comment by 390057892** [comment]
Pageloader类的loadPages方法通过breakText方法计算了一行的文字，但这个是按字符分割的，英文会被分割，解决方法就是对已经计算出来的wordCount再计算，计算方法大致就是找到当前字符串最后的空格符或者换行符。` if (!str.substring(str.length() - 1).equals(" ") && !str.endsWith("\n")) {
                                wordCount = str.lastIndexOf(" ") + 1;
                            }`

**Comment by luotext** [comment]
> 
> 
> Pageloader类的loadPages方法通过breakText方法计算了一行的文字，但这个是按字符分割的，英文会被分割，解决方法就是对已经计算出来的wordCount再计算，计算方法大致就是找到当前字符串最后的空格符或者换行符。` if (!str.substring(str.length() - 1).equals(" ") && !str.endsWith("\n")) { wordCount = str.lastIndexOf(" ") + 1; }`

好的，我现在就试试。

**Comment by luotext** [comment]
> 
> 
> > Pageloader类的loadPages方法通过breakText方法计算了一行的文字，但这个是按字符分割的，英文会被分割，解决方法就是对已经计算出来的wordCount再计算，计算方法大致就是找到当前字符串最后的空格符或者换行符。` if (!str.substring(str.length() - 1).equals(" ") && !str.endsWith("\n")) { wordCount = str.lastIndexOf(" ") + 1; }`
> 
> 好的，我现在就试试。


> 
> 
> Pageloader类的loadPages方法通过breakText方法计算了一行的文字，但这个是按字符分割的，英文会被分割，解决方法就是对已经计算出来的wordCount再计算，计算方法大致就是找到当前字符串最后的空格符或者换行符。` if (!str.substring(str.length() - 1).equals(" ") && !str.endsWith("\n")) { wordCount = str.lastIndexOf(" ") + 1; }`

我后面用了个判断
    private static boolean isTrue(String line) {
        return !line.endsWith(" ") &&
                !line.endsWith(",") &&
                !line.endsWith(".") &&
                !line.endsWith("-") &&
                !line.equals("\"");
    }
判断当前要绘制的行的末尾属于单词被切割的，如果是，那么将截取最后的空格str.substring(0, str.lastIndexOf(" ") + 1);为要绘制的内容，但是感觉判断特殊字符按，不是很好，因为特殊字符很多，而且，有些还是有用的。
