### ISSUE TITLE
绘制自定义view

### ISSUE THREAD

**Issue by CrazyShado** [390057892/reader#17]
你好，当前应用中的插画功能是基于drawbitmap的吗，如果我需要增加一个自定义view进去，如何实现自定义view跟随翻页动画进行翻页呢

**Comment by 390057892** [comment]
是通过drawBitmap实现的。想增加自定义view，绘制的时候判断。然后通过canvas画就行了。`private fun draw(
        canvas: Canvas,
        textLine: TextLine,
        relativeOffset: Float
    ) {
        val lineTop = textLine.lineTop + relativeOffset
        val lineBase = textLine.lineBase + relativeOffset
        val lineBottom = textLine.lineBottom + relativeOffset
        if (textLine.isImage) {
            drawImage(canvas, textLine, lineTop, lineBottom)
        } else {
            drawChars(
                canvas,
                textLine.textChars,
                lineTop,
                lineBase,
                lineBottom,
                isTitle = textLine.isTitle,
                isReadAloud = textLine.isReadAloud
            )
        }
    }`
