### ISSUE TITLE
Android 9 阅读时点击设置闪退

### ISSUE THREAD

**Issue by ColinTX** [390057892/reader#2]
Android 9 阅读时点击设置闪退

**Comment by ColinTX** [comment]
android.support.v7.widget.RecyclerView 这个问题 改androidx就好了
应该是你漏掉了。

**Comment by 390057892** [comment]
应该是迁移安卓x的时候设置布局没替换。稍等我改完会提交代码。

**Comment by ColinTX** [comment]
还缺个        ButterKnife.bind(this); 注解 哈哈

**Comment by 390057892** [comment]
因为正在用kt在重构。。本来已经删掉butterknife的，但工作量有点大。所以没去掉。代码提的时候比较着急。

**Comment by ColinTX** [comment]
嗯嗯 看着写的不错
