### ISSUE TITLE
小说阅读，上下滚动的时候，左下角页面的当前页会出现跳页的情况

### ISSUE THREAD

**Issue by jackom** [390057892/reader#5]
主要是指左下角的当前页，有时候上下滚动，会这样子显示： 18/61 跳到 20/61，来回滑动就会出现 18/61 跳到 20/61 或者 20/61 跳到 18/61。 另外上下滚动，有的内容中间的某一行会出现显示不全的情况：
![image](https://user-images.githubusercontent.com/5052960/69622852-b660ae80-107c-11ea-8f51-d821101dc29d.png)

**Comment by 390057892** [comment]
> 主要是指左下角的当前页，有时候上下滚动，会这样子显示： 18/61 跳到 20/61，来回滑动就会出现 18/61 跳到 20/61 或者 20/61 跳到 18/61。 另外上下滚动，有的内容中间的某一行会出现显示不全的情况：
> ![image](https://user-images.githubusercontent.com/5052960/69622852-b660ae80-107c-11ea-8f51-d821101dc29d.png)

滚动问题是因为 上拉时监听的顶部位置，顶部已经可以看到第一页了 所以显示1，往下拉时 监听的是底部位置，正好处于第二页时，下拉底部是第三页，所以显示3 。。显示不全是因为我间距计算出了偏差，导致电量变化重新绘制的时候会影响底部文字区域，最近有空会修改。

**Comment by jackom** [comment]
> > 主要是指左下角的当前页，有时候上下滚动，会这样子显示： 18/61 跳到 20/61，来回滑动就会出现 18/61 跳到 20/61 或者 20/61 跳到 18/61。 另外上下滚动，有的内容中间的某一行会出现显示不全的情况：
> > ![image](https://user-images.githubusercontent.com/5052960/69622852-b660ae80-107c-11ea-8f51-d821101dc29d.png)
> 
> 滚动问题是因为 上拉时监听的顶部位置，顶部已经可以看到第一页了 所以显示1，往下拉时 监听的是底部位置，正好处于第二页时，下拉底部是第三页，所以显示3 。。显示不全是因为我间距计算出了偏差，导致电量变化重新绘制的时候会影响底部文字区域，最近有空会修改。

那个跳页的应该是计算的时候出了问题导致的吧？如果以正常速度上下翻页，那样就没问题，如果上下翻页完成后，再快速的来回上下翻页，最后再以正常速度上下翻页，就会出现跳页的情况，我这边测试了好几次都一样的。
